# 1. Numpy Arrays

## 1.1 Create an array

### * Casting from a list

In [1]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [2]:
import numpy as np

arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
mtrx = np.array(my_matrix)
mtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### * Generate a new array

In [4]:
# arange(start, end, step)
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
# zeros(n): returns a 1-d array
np.zeros(5) 

array([ 0.,  0.,  0.,  0.,  0.])

In [6]:
# zeros((n,m)): returns a 2-d array, takes a tuple
np.ones((4,5)) 

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [7]:
# linspace(start, end, number_of_elements): different from arange(start, end, step), 
# takes 3rd argument as a numner of elements 
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [8]:
# eye(n): returns a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [9]:
# random array
np.random.rand(3, 2, 5)

array([[[ 0.05277681,  0.21301702,  0.82882589,  0.90851972,  0.13625668],
        [ 0.49854158,  0.49348186,  0.70039638,  0.84789112,  0.07800574]],

       [[ 0.94845719,  0.52760713,  0.67724992,  0.63953649,  0.39617599],
        [ 0.82164583,  0.84775677,  0.62867616,  0.68195124,  0.64342552]],

       [[ 0.81694021,  0.88136378,  0.28609553,  0.26389745,  0.69165467],
        [ 0.00396215,  0.33643833,  0.93427495,  0.10802835,  0.83789298]]])

In [10]:
# random normal distribution
np.random.randn(10,6)

array([[-0.33455773,  1.82572799,  0.51941081,  0.71450401,  0.00592777,
        -2.29396276],
       [-0.05274552, -0.09417454, -1.41567331,  0.66271446, -0.4321309 ,
        -0.95676562],
       [ 0.48981701, -0.42944537,  1.47238757,  0.46643494,  0.50401212,
        -0.10487404],
       [ 0.46065209, -1.47469456, -0.39508085, -1.00722176,  0.5311599 ,
         1.53887574],
       [-0.24823429, -1.52314364,  1.212654  ,  0.86873815,  0.28117063,
        -0.39130322],
       [-2.38654888,  0.4299724 ,  1.0696223 , -0.10105089, -1.98411602,
         0.01562421],
       [ 0.41100156,  0.81848429,  1.03912411, -0.01467852,  1.01750132,
         0.66612772],
       [-1.32465056, -1.09071575,  0.03346219,  0.84935048, -0.16842904,
        -0.1003525 ],
       [ 0.58042898, -1.07531731, -0.95662103,  0.20749088, -0.40658   ,
         0.5204478 ],
       [ 0.60643565, -0.47041108,  2.05177709,  1.85937653, -1.47008744,
        -0.42804278]])

In [11]:
# random int 
np.random.randint(5,10,3)

array([9, 5, 9])

### 1.2 Some useful methods

In [12]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
# reshape(row, col): row * col == n_element
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [14]:
rarr = np.random.randn(6)
rarr

array([ 0.05399371,  0.76181172,  1.62034356, -0.43526005, -0.28751203,
        0.94838389])

In [15]:
# find the max/min value of an array
rarr.max()

1.6203435638862378

In [16]:
# find the index of max/min value
rarr.argmax()

2

In [17]:
# get the shape property of an array: there is no '()' at the end.
rarr.shape

(6,)

In [18]:
# get the data type
rarr.dtype

dtype('float64')

# 2. Numpy Indexing and Selection