# 1. Numpy Arrays

## 1.1 Create an array

### * Casting from a list

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
import numpy as np

arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
mtrx = np.array(my_matrix)
mtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### * Generate a new array

In [6]:
# arange(start, end, step)
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
# zeros(n): returns a 1-d array
np.zeros(5) 

array([ 0.,  0.,  0.,  0.,  0.])

In [8]:
# zeros((n,m)): returns a 2-d array, takes a tuple
np.ones((4,5)) 

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [9]:
# linspace(start, end, number_of_elements): different from arange(start, end, step), 
# takes 3rd argument as a numner of elements 
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [10]:
# eye(n): returns a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [11]:
# random array
np.random.rand(3, 2, 5)

array([[[ 0.84057359,  0.86029577,  0.80700349,  0.3218885 ,  0.04873099],
        [ 0.13991128,  0.76150598,  0.29638425,  0.53328396,  0.05791499]],

       [[ 0.63372435,  0.24894523,  0.47566466,  0.33062211,  0.81018008],
        [ 0.5529384 ,  0.58837046,  0.98375782,  0.30523735,  0.19024477]],

       [[ 0.41088918,  0.56214767,  0.43010058,  0.13336566,  0.02582939],
        [ 0.24295473,  0.49604148,  0.01773793,  0.94364473,  0.74396508]]])

In [12]:
# random normal distribution
np.random.randn(10,6)

array([[-1.16743125,  2.9745634 ,  0.24150337, -1.08990063, -2.16652949,
         1.60650804],
       [-0.1453762 , -0.34350357, -1.46904967, -1.25343704, -0.0788975 ,
        -1.05295144],
       [ 0.93809387,  2.24736286, -2.28182837, -0.32906524, -0.18259141,
        -0.99077912],
       [ 0.78766408,  1.3141993 ,  2.08342856,  0.17781865,  1.30813634,
        -1.13867082],
       [-0.28404538,  0.70902499,  0.48612666,  0.04135574,  1.09512896,
         2.05175822],
       [-0.52831475, -0.17107138, -0.1987969 , -0.18052337, -1.20632728,
        -1.85579121],
       [ 2.64078014,  0.95629501,  0.66116782, -0.59390519,  0.18046821,
        -0.4776099 ],
       [-1.53708479,  0.22355046,  1.27381739,  0.762598  , -0.43853266,
         0.37312217],
       [ 1.14257779,  1.89829592, -2.28010888, -0.5622596 , -1.8060317 ,
        -0.70124786],
       [ 1.33598967, -0.44399293,  1.58520696,  0.22051145, -0.20019656,
         0.15687287]])

In [13]:
# random int 
np.random.randint(5,10,3)

array([8, 8, 9])

### 1.2 Some useful methods

In [14]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
# reshape(row, col): row * col == n_element
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
rarr = np.random.randn(6)
rarr

array([ 0.66157178,  0.06710124,  1.83253771, -1.41078996,  0.51164939,
       -0.00290521])

In [20]:
# find the max/min value of an array
rarr.max()

1.8325377119313708

In [21]:
# find the index of max/min value
rarr.argmax()

2

In [22]:
# get the shape property of an array: there is no '()' at the end.
rarr.shape

(6,)

In [23]:
# get the data type
rarr.dtype

dtype('float64')

# 2. Numpy Indexing and Selection

### * Indexing

In [24]:
rarr[3]

-1.4107899589682007

In [25]:
# slice
rarr[3:5]

array([-1.41078996,  0.51164939])

In [26]:
slice_of_arr = rarr[:4]
slice_of_arr

array([ 0.66157178,  0.06710124,  1.83253771, -1.41078996])

In [27]:
rarr[5:]

array([-0.00290521])

In [30]:
# broadcast an array
slice_of_arr[:]=99
slice_of_arr

array([ 99.,  99.,  99.,  99.])

In [31]:
# orginal array is changed as well (reference by default, not copy)
rarr

array([  9.90000000e+01,   9.90000000e+01,   9.90000000e+01,
         9.90000000e+01,   5.11649395e-01,  -2.90520892e-03])

In [32]:
# copy an array
arr_copy = arr.copy()
arr_copy[:] =100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [33]:
# original 
rarr

array([  9.90000000e+01,   9.90000000e+01,   9.90000000e+01,
         9.90000000e+01,   5.11649395e-01,  -2.90520892e-03])

### * 2-D array

In [35]:
# import numpy as np
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
# indexing a row
arr_2d[1]

array([20, 25, 30])

In [38]:
# indexing an element
arr_2d[2,1]

40

In [39]:
# slicing an 2-d sub-array
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

### * Conditional selection

In [45]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [47]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [48]:
# or with one line
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr<3]

array([1, 2])

In [51]:
# chunking
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
# select [24,25,35,35]
arr_2d[2:4,4:6]

array([[24, 25],
       [34, 35]])

## 3. NumPy operations
### * Array with Array

In [56]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### * Array with Scalars

In [60]:
arr * 0.2

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [61]:
arr / arr

/Users/Tandysony/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [62]:
1 / arr

/Users/Tandysony/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

### * Universal Array Functions

In [63]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [64]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [65]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [71]:
np.log(arr[1:])

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791,
        1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509])

#### More universal fucntions: https://docs.scipy.org/doc/numpy/reference/ufuncs.html